# Generated by Django 4.0.5 on 2023-06-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animent_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('state', models.CharField(max_length=60, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('cover', models.TextField(null=True)),
                ('author', models.CharField(max_length=60, null=True)),
                ('cartoon_voice', models.TextField(null=True)),
                ('synopsis', models.TextField(null=True)),
                ('video_url_list', models.TextField(null=True)),
                ('uptime', models.DateTimeField(null=True)),
                ('upyear', models.CharField(max_length=10, null=True)),
                ('language', models.CharField(max_length=50, null=True)),
                ('area', models.CharField(max_length=60, null=True)),
                ('tag_id', models.CharField(max_length=30, null=True)),
                ('click_nub', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': '动漫',
                'verbose_name_plural': '动漫',
            },
        ),
        migrations.CreateModel(
            name='cartoon_weekUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=50, null=True)),
                ('cartoonTitle', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='leave_word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urse', models.CharField(max_length=200, null=True)),
                ('content', models.TextField(null=True)),
                ('reply', models.TextField(null=True)),
                ('urse_img', models.ImageField(null=True, upload_to='')),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=60, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
