# Generated by Django 4.0.5 on 2023-06-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animentApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animent_table',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
