# Generated by Django 4.0.5 on 2023-07-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animentApi', '0002_animent_table_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_visit',
            name='visits_number',
            field=models.IntegerField(default=1),
        ),
    ]
