# Generated by Django 4.0.5 on 2023-07-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animentApi', '0003_user_visit_visits_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='animent_table',
            name='disk_number',
            field=models.IntegerField(default=1),
        ),
    ]
