# Generated by Django 4.0.5 on 2023-07-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimentLoginApi', '0001_initial'),
        ('animentApi', '0004_animent_table_disk_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave_word',
            old_name='urse',
            new_name='ursename',
        ),
        migrations.AddField(
            model_name='leave_word',
            name='up_user_message',
            field=models.ManyToManyField(related_name='sendChar', to='AnimentLoginApi.users_table'),
        ),
        migrations.AlterField(
            model_name='animent_table',
            name='click_nub',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='animent_table',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
