# Generated by Django 4.0.5 on 2023-08-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animentApi', '0006_animent_table_score_nub_alter_animent_table_upyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='animent_table',
            name='title_list',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user_visit',
            name='visits_history',
            field=models.TextField(null=True),
        ),
    ]
