# Generated by Django 4.0.5 on 2023-07-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimentLoginApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_table',
            name='user_cover',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
