# Generated by Django 4.0.5 on 2023-08-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimentLoginApi', '0002_users_table_user_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_table',
            name='user_last_login',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
