# Generated by Django 4.0.5 on 2023-08-12 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AnimentLoginApi', '0003_alter_users_table_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commonlyCode', models.CharField(max_length=10, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AnimentLoginApi.users_table')),
            ],
        ),
    ]
